### ISSUE TITLE
Need contribution help to upgrade this to Federation 2?

### ISSUE THREAD

**Issue by andrewstec** [apollographql/supergraph-demo-k8s-graph-ops#125]
@prasek 

I see you have been spearheading all of the supergraph repo work. Is there a plan to upgrade this repo for federation 2? I am wondering if I should fork this and start playing with it using federation 1.

Alternatively, I can help:

1. If the upgrade work is fairly straight-forward and you can summarize the work, or point me to the upgrade guide in the documentation. If there isn't too much complexity regarding telemetry in Kubernetes and the upgrade, I can see if I can help.
2. https://github.com/apollographql/supergraph-demo <-- Perhaps the upgrade work should occur here instead?
3. Or finally, perhaps we should just add K8s and Git Ops work to the repo here? https://github.com/apollographql/supergraph-demo-fed2

We can also break this upgrade task into smaller tasks and merge small contributions into a working branch. You probably don't want to maintain all three repos :-) I'm experienced on Node JS, Docker, and a certified Kubernetes Administrator (but still a bit green in Kubernetes). I am picking up GraphQL and getting back into React. Then I saw this project. It's a good mix of everything I am interested in...

**Comment by prasek** [comment]
Hi @andrewstec! This is an experimental repo and is not being actively maintained, so we'll be archiving it soon.

Many folks have already [migrated to Federation 2](https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2) and [apollographql/supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2) is being actively maintained. If you're going to start using something new, suggest starting with the Fed2 repo and using Apollo Router for your Federation runtime. The [latest Federation docs](https://www.apollographql.com/docs/federation/) are a great place to get started with both.

Note we've aimed to keep [apollographql/supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2) as slim as possible, so have removed the [k8s examples that were in the older supergraph-demo](https://github.com/apollographql/supergraph-demo/tree/main/k8s). It's possible we could resurrect those, but it would add a bit more complexity to the demo.

Also note there are [Apollo Router k8s docs for the helm chart it provides](https://www.apollographql.com/docs/router/containerization/kubernetes) which includes a lot of template files, so those are a good reference as well.

If you just want to experiment with some of the more advanced concepts here, would suggest forking this repo and just upgrading to Fed 2 and the Router. However if you're looking for best-practices at scale, would recommend checking out the [Enterprise Guide](https://www.apollographql.com/docs/enterprise-guide/introduction) as a better starting point than this repo.
